### ISSUE TITLE
Error when there is a symlink in the repo

### ISSUE THREAD

**Issue by cadadr** [clemera/dired-git-info#1]
I have a symlink `config.m4` in my repo which is a link to `some-file`.  This causes this feature to show the following message on the line of the symlink in the dired buffer:

    fatal: ambiguous argument 'config.m4 -> some-file': unknown revision or path not in the working tree

The other lines are not affected.

Apparently it is taking the `linkname -> target` string as the file name, where it'd rather only use `linkname`.

**Comment by ghost** [comment]
The following patch seems to help but it is hackish (would fail if the string ` ->` was ever part of a filename).  IDK much about what "dired collapse" does but there should be a better way to get the file name w/o resorting to substringing the buffer.

```
diff -uNp --label /home/g/cf/emacs.d/lisp/site/misc/dired-git-info.el --label \#\<buffer\ dired-git-info.el\> /home/g/cf/emacs.d/lisp/site/misc/dired-git-info.el /tmp/buffer-content-5i8SV1
--- /home/g/cf/emacs.d/lisp/site/misc/dired-git-info.el
+++ #<buffer dired-git-info.el>
@@ -103,6 +103,8 @@ info format and defaults to `dgi-commit-
                      (save-excursion
                        (dired-goto-file file)
                        (buffer-substring (point) (line-end-position))))))
+    (when (file-symlink-p file)
+      (setq lfile (car (split-string lfile " ->"))))
     (when (and lfile (not (member lfile '(".." "."))))
       (let ((msg (dgi--command-to-string
                   "git" "log" "-1"
```

**Comment by clemera** [comment]
Thanks for the report! I just pushed some changes,  could you test again with the recent version?

**Comment by clemera** [comment]
> there should be a better way to get the file name w/o resorting to substringing the buffer

The problem is I need to determine what the actual displayed file name looks like, to get the formattiing right.

**Comment by ghost** [comment]
You’re welcome!  Sorry for the delay, I could not get on my computer for
the last couple of days.

The changes fixed it for me.

**Comment by clemera** [comment]
Thanks!
