### ISSUE TITLE
dired-git-info-mode not working with tramp

### ISSUE THREAD

**Issue by nyqvist** [clemera/dired-git-info#2]
Hi,

When using dired-git-info-mode in a buffer opened via tramp I get this message printed out for all files in the repository:
"fatal: Invalid object name '/ssh'."

![skarmbild_2019-02-21_08-37-12](https://user-images.githubusercontent.com/1544300/53169002-595f3600-35dc-11e9-82c6-00d4dfd7b2cf.png)

**Comment by clemera** [comment]
Thanks for the report, should be fixed now, can you retry with the recent version?

**Comment by nyqvist** [comment]
Thanks! It works now.
