### ISSUE TITLE
Limit commit message display upto 80 chars

### ISSUE THREAD

**Issue by Compro-Prasad** [clemera/dired-git-info#3]
![screenshot from 2019-02-27 14-27-11](https://user-images.githubusercontent.com/11143962/53478004-e4887200-3a9b-11e9-8336-51fede4f2cc9.png)

**Comment by manuel-uberti** [comment]
IMHO, this could be a new `defcustom`.

**Comment by clemera** [comment]
Fixed by 9f34bd7b462ca39455f4036d3afab06661620444

**Comment by clemera** [comment]
Thanks for your report by the way!
