### ISSUE TITLE
How to hack string clamping to leave date intact?

### ISSUE THREAD

**Issue by sarg** [clemera/dired-git-info#5]
As a workaround I'm currently using:
```elisp
(setq dgi-commit-message-format "%<(80,trunc)%s %cr")
```
It works fine but doesn't respect window width. Maybe there is a simple way to do that I don't recognize?

**Comment by clemera** [comment]
You could exchange the columns of date and message:

    "%cr\t%s"

A function could be added to create the format to use which would allow more freedom how to format the message.

**Comment by sarg** [comment]
Ah, that's ingenious. Thanks, that's enough for me. Feel free to close the issue.
