### ISSUE TITLE
Columns aren't aligned

### ISSUE THREAD

**Issue by hmelman** [clemera/dired-git-info#7]
I have `dgi-commit-message-format` set to the default "%s\t%cr" but the change times are not aligned as shown in the image or mentioned in the docstring, "Entries separated by tabs are aligned." Instead on each line the time is separated by one tab from the end of the previous text. 

I tried tracking through `align-regexp` but got lost.

**Comment by clemera** [comment]
Don't know what could cause this. Have you tried with a fresh `emacs -Q` session? If its not happening there, it is probably related to your config.

**Comment by hmelman** [comment]
Fails the same way with emacs -Q. I'm on macOS 10.14.6 running the most recent "mac port". Gnu Emacs 26.3 (build 1, x86_64-apple-darwin18.5.0, Carbon Version 158 AppKit 1671.4) of 2019-12-03.

To be clear the first column is the filename, the second is the commit message which is aligned. The third (after the tab) is the relative date which isn't aligned.

**Comment by clemera** [comment]
What happens if you evaluate the following in the scratch buffer:

    (insert
     (with-temp-buffer
       (insert "\n")
       (dolist (message '("hello\tweird\tbug" "are\tyou\tthere?"))
         (insert message "\n")
         (align-regexp (point-min)
                       (point-max)
                       "\\(\\s-*\\)\t" nil nil t))
       (buffer-string)))

Is the inserted text aligned?

**Comment by clemera** [comment]
If the above is aligned maybe the tab character gets lost somewhere in between. What if you replace tab with another character like `_`?

    (setq dgi-commit-message-format "%s_%cr")

    (defun dgi--get-commit-messages (files)
      "Get formatted commit messages for FILES."
      (let ((messages ()))
        (dolist (file files)
          (push (dgi--get-commit-info file)
                messages))
        (with-temp-buffer
          (dolist (message (nreverse messages))
            (insert (or message "") "\n"))
          (align-regexp (point-min)
                        (point-max)
                        "\\(\\s-*\\)_" nil nil t)
          (goto-char (point-min))
          (while (search-forward "\t" nil t)
            (replace-match " "))
          (split-string (buffer-string) "\n"))))

**Comment by hmelman** [comment]
Yes, evaluating that in the *scratch* buffer was aligned. No, changing it to _ and using the new `dgi--get-commit-messages` didn't align the 3rd column.

**Comment by clemera** [comment]
Have you tried it in different repositories? Other than that I'm out of ideas ;)

**Comment by hmelman** [comment]
I have, in two different ones. Same behavior. I had the same problem with the 0.2 release.

It turns out your test case above with _ had a bug. You changed align_regexp to use _ but further down the search-forward still used "\t". If I change that to _ I get different behavior. Most of the relatives dates are aligned, though about a third have an extra tab and are one tab too far to the right. It doesn't seem to correlate with the length of the commit summary.  Since _ is in some of my summaries, I tried using @ instead of _ and saw the same results.

**Comment by clemera** [comment]
Oh a test case with bugs, that's great ;) sorry for that! Maybe the messages contain leading white space themselves (or are returned with white space) from `dgi--get-commit-info`?

**Comment by hmelman** [comment]
Looking at the `messages` created by the `dolist` call to `dgi--get-commit-info` I see some nil values and a bunch of strings, none of which have leading or trailing whitespace. All seem to have one tab between the summary and relative date. e.g.: "some frame stuff	8 months ago" (there's a single tab before the 8 if it doesn't come through github).

**Comment by clemera** [comment]
Here is another try:

    (setq dgi-commit-message-format "%s///%cr")

    (defun dgi--get-commit-messages (files)
      "Get formatted commit messages for FILES."
      (let ((messages ()))
        (dolist (file files)
          (push (dgi--get-commit-info file)
                messages))
        (with-temp-buffer
          (dolist (message (nreverse messages))
            (insert (or message "") "\n"))
          (align-regexp (point-min)
                        (point-max)
                        "\\(\\s-*\\)///" nil nil t)
          (goto-char (point-min))
          (while (search-forward "///" nil t)
            (replace-match ""))
          (split-string (buffer-string) "\n"))))

Does the above work?

**Comment by clemera** [comment]
If not the problem is probably in the body of `dired-git-info-mode` itself when creating the overlays using `dgi--get-dired-file-length`.

**Comment by hmelman** [comment]
It behaves exactly the same as the fixed _ version.  For some lines, the 3rd column seems extra indented by one tab stop.

I've been having trouble trying to describe the formatting exactly since I can't navigate into that part of the buffer. But, enabling `whitespace-mode` shows the 2nd column (summary) is properly aligned using spaces and the 3rd column (relative date) uses tabs.

![Screen Shot 2019-12-14 at 1 06 32 PM](https://user-images.githubusercontent.com/1999190/70852702-98fc5480-1e72-11ea-9562-4efd6187a994.png)

**Comment by clemera** [comment]
Oh actually I can reproduce this with `emacs -Q` so it is MY config which hides the bug :D Now that I can reproduce this I hope I find the problem.

**Comment by clemera** [comment]
I think the culprit is the indent-tabs-mode setting, can you try with:
    
    (setq-default indent-tabs-mode nil)

**Comment by hmelman** [comment]
Yes, that solves it.

**Comment by clemera** [comment]
Nice! Here is a quick fix I will later update the repo:

    (defun dgi--get-commit-messages (files)
      "Get formatted commit messages for FILES."
      (let ((messages ()))
	(dolist (file files)
	  (push (dgi--get-commit-info file)
		messages))
	(with-temp-buffer

	  (dolist (message (nreverse messages))
	    (insert (or message "") "\n"))
	  (let ((indent-tabs-mode nil))
	    (align-regexp (point-min)
			  (point-max)
			  "\\(\\s-*\\)\t" nil nil t))
	  (goto-char (point-min))
	  (while (search-forward "\t" nil t)
	    (replace-match " "))
	  (split-string (buffer-string) "\n"))))

**Comment by hmelman** [comment]
Yes, that works. Thank you.

**Comment by clemera** [comment]
Thank you, too! You are probably not the only one who had the issue but if no one complaints it can't get fixed ;)
