### ISSUE TITLE
Error installation from GNU ELPA

### ISSUE THREAD

**Issue by yuravg** [clemera/dired-git-info#8]
Hello,
i try install your package from ELPA
`M-x package-install RET dired-git-info RET`

but installation abort with error
`
Failed to verify signature dired-git-info-0.3.1.el.sig:
No public key for 066DAFCB81E42C40 created at 2019-12-15T03:20:03+0300 using RSA
Command output:
gpg: Signature made Sun 15 Dec 2019 03:20:03 AM MSK
gpg:                using RSA key C433554766D3DDC64221BFAA066DAFCB81E42C40
gpg: Can't check signature: No public key
`

I can install other ELPA packages without errors.
Maybe your last package has an error? or a problem with my Emacs configuration?

**Comment by clemera** [comment]
Please checkout [this](https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html) post and if it helps you to fix the problem.

**Comment by yuravg** [comment]
> Please checkout [this](https://metaredux.com/posts/2019/12/09/dealing-with-expired-elpa-gpg-keys.html) post and if it helps you to fix the problem.

That helped
Thanks, for your help

**Comment by clemera** [comment]
Great!
